### ISSUE TITLE
No way to remap controller topics

### ISSUE THREAD

**Issue by mikepurvis** [ros-controls/ros_controllers#126]
Most problematic with diff_drive_controller, as it means your main command topic ends up as `/my_velocity_controller/cmd_vel` rather than `/cmd_vel`. If it's your own controller manager, you can pass remaps into the NodeHandle, but none of that works if it's Gazebo's.

One option is for controllers to just parameterize key topic names, but remapping is an important aspect of ROS's modularity strategy— not having this work in a standardized way seems undesirable.

In the short term, I can just use a topic_tools/relay, but that seems like a pretty non-optimal strategy as well.

Thoughts?

**Comment by bmagyar** [comment]
We are using higher level components to manage who commands the controllers or which commands should make it through so it was desirable to not have the controller taking commands from that topic directly.
If you have no need for a man-in-the-middle, I'd suggest sticking with the relay. 
If we add a parameter to the controller to specify the topic name, that would somehow go against the common practice of remapping in ROS. 

Maybe we could investigate how to provide remapping with gazebo plugins.

**Comment by adolfo-rt** [comment]
Is there any inconvenient to remap on the publisher side?

**Comment by mikepurvis** [comment]
@adolfo-rt It's no good to remap on the publisher side because a topic like cmd_vel forms part of the user-facing API of the robot.

@bmagyar The higher level components for us will be things like `move_base`, but it could be lots of different things, including user-specified.

The ideal would be if remaps could be declared via `<remap>` tags on the controller_spawner script.

**Comment by efernandez** [comment]
@mikepurvis We simple left `/mobile_base_controller/cmd_vel` as it is, because add the end you need some system to multiplex between the different commanding inputs, like the joystick, `move_base` navigation, or others like a tablet or even the keyboard teleop.

We remap on the publisher side for that reason; if not, for you'd have to use topic_tools relay.

**Comment by bmagyar** [comment]
We have a tool that is similar to [cmd_vel_mux from Yujin](http://wiki.ros.org/cmd_vel_mux) that manages inputs from joystick, keyboard, navigation, etc. If there is interest I believe we could publish it on github.

**Comment by mikepurvis** [comment]
Seems reasonable. Would be happy to have that in the teleop org if you'd like to contribute it there: https://github.com/ros-teleop

**Comment by efernandez** [comment]
@mikepurvis That sounds really good!
@po1 Maybe we can also include other pkgs already online.

@lucamarchionni I think we can make our `twist_mux` public, since there's already something pretty similar from [Yujin](http://wiki.ros.org/cmd_vel_mux) and we can benefit of having it inside `ros-teleop`. What do you think?

**Comment by bmagyar** [comment]
big +1 for `ros-teleop`

**Comment by po1** [comment]
> @po1 Maybe we can also include other pkgs already online.

Yes. We have a few tools for teleoperation [here](https://github.com/pal-robotics/teleop_tools). In particular, `joy_teleop` is a very versatile joystick interface that maps analog sticks to topics (or fields thereof) and buttons (or combinations of buttons) to actions. @mikepurvis have a look at its [sample config file](https://github.com/pal-robotics/teleop_tools/blob/hydro-devel/joy_teleop/config/joy_teleop.yaml). It looks like yet more work was duplicated, but it's never too late to combine efforts!

**Comment by mikepurvis** [comment]
Haha, everyone writes their own "generic teleop" for ROS.

Well, for now, the question here is answered.

**Comment by contradict** [comment]
For those who arrive here in despair in the future, all hope is not lost. Remaps can be applied to the controller manager (usually `ros2_control_node`) instead of the spawner and will be applied to the controller when it is loaded. My use case was renaming `joint_states` so that I could use `joint_state_publisher` to combine multiple sources of joint information, including some default values for unused joints.

**Comment by bmagyar** [comment]
I'd definitely be worried if many arrived here and would not notice that this is a ROS1 repo ;)

**Comment by contradict** [comment]
Yeah, unfortunately it is still the first Google result for remapping ros2 control.
