### ISSUE TITLE
Hydro release is stuck at 0.7.2?

### ISSUE THREAD

**Issue by y22ma** [ros-controls/ros_controllers#130]
The hydro release version is still 0.7.2, and it's missing alot of features (e.g. frame id parametrization for base frame). Would appreciate it if a release can be pushed to the build farm.

**Comment by adolfo-rt** [comment]
> The hydro release version is still 0.7.2, and it's missing alot of features (e.g. frame id parametrization for base frame).

There have actually been very few changes in hydro since 0.7.1. I believe e3a589e19abea114db50b202fa004df22c049183 (what you're interested in) is the only new feature, all the rest has been build system bugfixes.

> Would appreciate it if a release can be pushed to the build farm.

Considering my previous statement, the hydro release has been held for a simultaneous release with indigo, which in contrast has seen a significant number of new features.

A patch release for hydro and a minor version bump for indigo are planned for the near future. These last days we have been in the process of merging pending pull requests. If the prerelease tests come out clean, we can start thinking of a release.

**Comment by adolfo-rt** [comment]
See #134.

**Comment by adolfo-rt** [comment]
https://github.com/ros/rosdistro/pull/6106
