### ISSUE TITLE
Velocity Controller behavior when vel=0

### ISSUE THREAD

**Issue by davetcoleman** [ros-controls/ros_controllers#36]
Hi guys,

What is the desired behavior of a velocity controller when its setpoint velocity is 0? It seems that if you just have a PID controller trying to maintain 0 velocity on the joint, as is the case with `ros_controllers/effort_controllers/joint_velocity_controller.cpp`, your joint will slowly drift with error to a gravity-neutral state. For example, a robot arm will gradually fall down until it reaches its joint limits. 

A [solution I just implemented](https://github.com/davetcoleman/ros_controllers/blob/velocity_position_controller/effort_controllers/src/joint_velocity_controller.cpp) is to have the velocity controller switch to a "position-controller" mode when its set to 0 velocity, so as to maintain position and not drift.

Is this a feature I should try to merge into the default velocity_controller? Should it be an option in the `init()` function? Off or on by default?

**Comment by bobholmberg** [comment]
Dave,

Since this is a special mode of a completely general velocity controller, I
would make it an option and leave it off by default.  I can see how it
would be useful, and acknowledge some would prefer to init their robot with
it turned on.  For those who understand what it does and want it on, they
should turn it on explicitly.

There could be some surprises at very low velocities when transitioning
between modes if there is a higher level controlling the joints that have
been configured in velocity control.  When making a wheeled base with
steered and driven wheels, one good way to control the base is to put the
joints into velocity control and have a base-controller dispatching joint
velocity commands to the joints.  In this case you would not want the
discontinuity of the mode switch.

--Bob

**Comment by adolfo-rt** [comment]
I also agree that a simple velocity PID loop should be the default. I don't mind having an optional position controller for the zero-velocity case if there are good usecases behind. Still, since this is supposed to be a simple, general purpose controller, I'd be cautious about a few things:

Currently the zero-velocity check is against [exactly zero](https://github.com/davetcoleman/ros_controllers/blob/velocity_position_controller/effort_controllers/src/joint_velocity_controller.cpp#L152). It might well be the case that a joint command is the result of arithmetic operations (eg. a task -> joint space mapping), and that the value is close to --but not exactly-- zero due to roundoff errors. Under such circumstances the position mode would never kick in.

Getting good velocity estimates at near-zero velocity is in fact the source of the problem, and this is unfortunately application-specific. What we really want is that the (optional) position mode kicks in when the joint velocities are near-zero, _and_ below the point where we can get a good estimate. As @bobholmberg states, we'd also like the transition to this mode to be smooth.

**Comment by davetcoleman** [comment]
Thanks for the feedback. The easiest solution would be to just create another controller within the effort_controllers package that has this specialization in it. I'd like to contribute this feature back but I don't have the time to try to add new features to an existing controller that might break code that is currently depending on it, unless you guys think this is worth the effort.

What magic number should I use for the tolerance to check the zero-velocity value? Something like +/- 10^-5 ?

**Comment by chadrockey** [comment]
Magic ROS param.

**Comment by adolfo-rt** [comment]
> Magic ROS param.

Yeah, expose it as a parameter, but provide a sensible default in case it's unspecified.

**Comment by davetcoleman** [comment]
I no longer need this feature, closing.

**Comment by cpacchierotti** [comment]
This issue is still present in the latest version (0.10.0-1trusty-20160423-015217-0700).

**Comment by bmagyar** [comment]
No surprise there. As far as I see on the discussion above and the git log of the relevant file, no pull request was opened. If you have a solution for it, feel free to open a pull request against kinetic-devel.
