### ISSUE TITLE
Can I use the controller in an sdf description?

### ISSUE THREAD

**Issue by zapplelove** [ros-controls/ros_controllers#375]
My robot has many loops, so I can't use the urdf file to decribe my robot but sdf. But when I use the plugin tag to load libgazebo_ros_control.so, I realize that controllers are just supportting urdf description instead of sdf. So HOW CAN I CONTROL MY ROBOT?

**Comment by bmagyar** [comment]
Hello,

Thank you for your interest in `ros_control`.
Indeed `ros_control` currently doesn't support loading SDF files just as well as many visualizers and kinematics libraries. We would be happy to accept pull requests from you implementing this feature. You may also need to enable using SDF instead of urdf on other ROS components depending on the `/robot_description` parameter.

Best,
Bence
