### ISSUE TITLE
Complete description for position interface

### ISSUE THREAD

**Issue by davetcoleman** [ros-controls/ros_controllers#49]
@adolfo-rt, could you provide please the complete description for the position interface of the joint_trajectory_controller on [this page](https://github.com/ros-controls/ros_controllers/tree/hydro-devel/joint_trajectory_controller)? The complete is provided for the effort interface but I know they are not exactly the same (no PID gains, for example).

Thanks!

**Comment by adolfo-rt** [comment]
I'm currently writing a [ros wiki page](http://wiki.ros.org/joint_trajectory_controller) for the controller. I expect it to be complete within the day. I'm using the ROS wiki because documenting the ROS API is much easier there. We can then point the README.md to the wiki.

I'd like to discuss the more general topic of where to put what interms of documentation. I'll open a separate issue on ros_control for that.

**Comment by davetcoleman** [comment]
Thanks again adolfo!
Fixed in https://github.com/ros-controls/ros_control/issues/119#issuecomment-25448455
