### ISSUE TITLE
Differential drive plugin not working 

### ISSUE THREAD

**Issue by SaailN** [ros-controls/ros_controllers#498]
![roserror](https://user-images.githubusercontent.com/40292489/87897164-1969e000-ca68-11ea-8877-af1f3f6781f1.png)
Differential drive plugin is giving me the following warnings and is not working in ROS kinetic
.

**Comment by bmagyar** [comment]
I suggest you ask the same question over at the gazebo plugins as your issue is with that, not the controller. They have the same name but it's quite different.

https://github.com/ros-simulation/gazebo_ros_pkgs/blob/kinetic-devel/gazebo_plugins/include/gazebo_plugins/gazebo_ros_diff_drive.h

At the same time I'd invite you to try using ros_control with your gazebo robot. 
http://gazebosim.org/tutorials/?tut=ros_control
