### ISSUE TITLE
The effort-based joint position controller can lose commands

### ISSUE THREAD

**Issue by jim-rothrock** [ros-controls/ros_controllers#51]
If a single command is sent to an effort-based joint position controller via a latched publisher, the command can be lost. Here is the sequence of events:

1) A position command is published with a latched publisher.
2) JointPositionController::setCommandCB() is called. It calls JointPositionController::setCommand(), passing it the position.
3) JointPositionController::setCommand() stores the position in command_struct_.position_.
4) JointPositionController::update() is about to be called for the first time, so JointPositionController::starting() is called.
5) JointPositionController::starting() stores the joint's position in command_struct_.position_, overwriting the value received from the publisher.

For a test case, run the following in a directory that's in your ROS path:

git clone https://github.com/wunderkammer-laboratory/ackermann_vehicle.git
roslaunch ackermann_vehicle_gazebo pub_problem.launch

In the Gazebo window that is displayed, you'll see that the vehicle's shock absorbers are not activated, i.e. the chassis is below the wheel's axles. To see how the vehicle should look, run this:

roslaunch ackermann_vehicle_gazebo ackermann_vehicle.launch

This second case works because the shock absorber positions are sent in the main loop, once per second.

I don't know if "the joint controller might lose commands for a short period of time" is the controller's intended behavior. If not, I've found that the problem can be fixed by taking the code above command_.initRT(command_struct_) in JointPositionController::starting() and moving it to the end of JointPositionController::init(), then moving the initialization of sub_command_ to the position immediately following the moved block of code.

**Comment by adolfo-rt** [comment]
Jim,

I consider it expected behavior to ignore commands sent before the controller is started. Still, the controller can be improved in two trivial ways:
- Document that `starting()` holds the current position, as in the [joint trajectory controller](https://github.com/ros-controls/ros_controllers/blob/hydro-devel/joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller.h#L137).
- Do a no-op in the [command callback](https://github.com/ros-controls/ros_controllers/blob/hydro-devel/effort_controllers/src/joint_position_controller.cpp#L224) if the controller is not running. The joint trajectory controller also [does this](https://github.com/ros-controls/ros_controllers/blob/hydro-devel/joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller_impl.h#L428).

On your end of things, can you adapt your setup to not depend on a latching publisher?. You're the first person I know of that tries to use the controller with a latched topic. I think all other controllers inside ros_controllers behave in a similar way.

**Comment by jim-rothrock** [comment]
> On your end of things, can you adapt your setup to not depend on a latching publisher?

Is there a way for a node to tell (via ROS topics) whether a controller has started? If not, it seems as if the only robust way to use <controller name>/command topics is to publish to them periodically, even if the message is always the same.

**Comment by adolfo-rt** [comment]
> Is there a way for a node to tell (via ROS topics) whether a controller has started?

The controller-agnostic (and preferred) way of doing it is by calling the `controller_manager/list_controllers` service. It gives you a lot of useful info. Example output:

``` yaml
controller:
  - 
    name: head_controller
    state: running
    type: position_controllers/JointTrajectoryController
    hardware_interface: hardware_interface::PositionJointInterface
    resources: ['head_1_joint', 'head_2_joint']
  - 
    name: torso_controller
    state: stopped
    type: position_controllers/JointTrajectoryController
    hardware_interface: hardware_interface::PositionJointInterface
    resources: ['torso_1_joint', 'torso_2_joint']

```

You could also check for controller-specifics like have an action client wait until the server is up and running. You could check if a service exists, or if a topic has subscribers, but I don't recommend this approach for topics and services, as the `controller_manager/list_controllers` probably does what you want in a more general way.

> If not, it seems as if the only robust way to use <controller name>/command topics is to publish to them periodically, even if the message is always the same.

Just for safety's sake. I would try to put some logic in place that only sends commands when the requisites are there. Scary things can happen if the controller starts and encounters commands with far away references.

**Comment by jim-rothrock** [comment]
Okay, thanks. I'll use controller_manager/list_controllers. I'm closing this issue.
