### ISSUE TITLE
New releases reverted on Noetic due to Debian builds failing for diff_drive_controller

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros_controllers#537]
https://github.com/ros/rosdistro/issues/27401

Version 0.17...  build, 0.18... fails. 
Look for  `boost_headers` in the log to find the error
http://build.ros.org/view/Nbin_db_dB64/job/Nbin_db_dB64__diff_drive_controller__debian_buster_amd64__binary/

**Comment by bmagyar** [comment]
@mateus-amarante @matthew-reynolds do you guys have any spare bandwidth to look into this?

**Comment by mateus-amarante** [comment]
I'll take a look at it tomorrow.

**Comment by matthew-reynolds** [comment]
Looks like the issue is the version of CMake.

The `FindBoost` macro uses `Boost::headers` for header-only libraries as of 3.15, but before that it was `Boost::boost`. Looks like Debian Buster uses CMake 3.13. (Out of interest, the required/recommended CMake versions in REP 0003 are a bit all over the place and don't give an easy version-proof solution to this).

The easy fix is to just go back to `find_package(Boost REQUIRED)`, rather than `find_package(Boost REQUIRED COMPONENTS headers)` or `find_package(Boost REQUIRED COMPONENTS boost)`. Anyways, that's how the examples in the FindBoost documentation handle header-only, and how we currently do it in `joint_trajectory_controller`, so should be all good.

**Comment by bmagyar** [comment]
Thanks for the quick assistance on this guys!
