### ISSUE TITLE
I Can't built package.

### ISSUE THREAD

**Issue by niboon39** [ros-controls/ros_controllers#571]
![image](https://user-images.githubusercontent.com/30637687/127477687-1e9a5591-717c-4628-8566-a7dc99c53c9d.png)

**Comment by matthew-reynolds** [comment]
As the error message says, you're missing the `four_wheel_steering_msgs` package, which the `four_wheel_steering_controller` depends on. You need to make sure you grab all the dependencies. The easiest way is with rosdep. You can automatically install all deps for all packages in your workspace with `rosdep install --from-paths src --ignore-src`

If you have some good reason for not just using rosdep, you can manually install it instead. Either install it to your main ROS installation (ie. `apt install ros-noetic-four-wheel-steering-msgs`) and be sure to source `/opt/ros/noetic/setup.bash`, or clone it into your local workspace `~/urdf_ws/src` (Repo is here: https://github.com/ros-drivers/four_wheel_steering_msgs). You will likely have to do this for a bunch of packages, since there's a good chance you're missing other deps too.

Alternatively, if you're not using the `four_wheel_steering_controller`, you could just skip building it. There are a lot of controllers in this repo and you might not need them all.

I'm going to close this issue as I have hopefully given you the info you need. In future, please ask these kinds of questions on answers.ros.org. This is also a pretty basic issue, so a quick search before opening a new questions would be appreciated. Here's a very similar question I found with a quick Google search: https://answers.ros.org/question/283636/catkin_make-four_wheel_steering_msgs-pkg-not-found/
