### ISSUE TITLE
JointTrajectoryController - spline interpolation strategy

### ISSUE THREAD

**Issue by fzoric8** [ros-controls/ros_controllers#626]
Hi, 

I'm wondering if it is possible to specify different interpolation method for the `JointTrajectoryControler`. 

[Here](http://wiki.ros.org/joint_trajectory_controller) in the **1.1. Trajectory representation** section, multiple  spline interpolation strategies are specified, but I'm not 
sure is it possible to change it from Quintic to Linear and how to do so. 
There's no parameter specification in the wki. 

As far as I'm able to see, Quintic interpolation is default in the `.cpp` source, but for my specific use-case I would
need `Linear` spline interpolation. 

So if there's a way to change spline interpolation strategy for the `joint_trajectory_controller` please let me know. 

Thanks!

**Comment by dcconner** [comment]
If you only specify positions it does linear interpolation.  To do cubic you need to specify both position and velocity, and quintic needs position, velocity, and acceleration at each knot point.  It uses the appropriate interpolation based on the data provided.

This means that you need to be careful in specifying data at knot points because the quintic interpolation can generate some wild curves to satisfy the constraints at the knot points.  The advantage is you can guarantee bounded jerk with continuous accelerations.

**Comment by fzoric8** [comment]
Nice, thanks for the quick answer!
